### ISSUE TITLE
Invalid Syntax Error when doing anything

### ISSUE THREAD

**Issue by Czechball** [ArchiveTeam/wpull#436] opened 2019-10-06 19:28 UTC
*What I wanted:* Try out the `wpull google.com/about` command from readme
 
*What I expect:* I expect it to download the about page

*What happened:* I got a `SyntaxError: invalid syntax`

*The command or website causes the problem:* ``wpull google.com/about``

*Operating system:* Arch Linux - `5.3.1-arch1-1-ARCH`

*Python version:* Python 3.7.4

*Wpull version:* Wpull 2.0.1

*Log/Output:*

```
Traceback (most recent call last):
  File "/usr/bin/wpull", line 11, in <module>
    load_entry_point('wpull==2.0.1', 'console_scripts', 'wpull')()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3.7/site-packages/wpull/application/main.py", line 4, in <module>
    from wpull.application.builder import Builder
  File "/usr/lib/python3.7/site-packages/wpull/application/builder.py", line 12, in <module>
    from wpull.application.tasks.download import ProcessTask, ParserSetupTask, ClientSetupTask, ProcessorSetupTask, \
  File "/usr/lib/python3.7/site-packages/wpull/application/tasks/download.py", line 10, in <module>
    from wpull.processor.coprocessor.phantomjs import PhantomJSParams
  File "/usr/lib/python3.7/site-packages/wpull/processor/coprocessor/phantomjs.py", line 19, in <module>
    from wpull.driver.phantomjs import PhantomJSDriverParams, PhantomJSDriver
  File "/usr/lib/python3.7/site-packages/wpull/driver/phantomjs.py", line 10, in <module>
    from wpull.driver.process import Process
  File "/usr/lib/python3.7/site-packages/wpull/driver/process.py", line 56
    self._stderr_reader = asyncio.async(self._read_stderr())
                                      ^
SyntaxError: invalid syntax
```

**Comment by JustAnotherArchivist** [comment] 2019-10-07 19:46
Resolved on IRC (wpull only supports Python 3.4 to 3.6); duplicate of #404

**Closed by JustAnotherArchivist** 2019-10-07 19:46 UTC
